version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ayuki
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: financial_report
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  ollama:
        image: ollama/ollama
        ports:
            - "11434:11434"
        volumes:
            - ollama_data:/root/.ollama
        restart: always
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      # 6333: REST API, 6334: gRPC API :contentReference[oaicite:0]{index=0}
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__service__storage__use_mmap=true

volumes:
  pgdata:
  ollama_data:
  qdrant_data:
